version: '3.8'
services:
  indexhub_local:
    image: postgres:10-alpine
    container_name: PG_Database
    ports:
      - ${POSTGRES_PORT}:${PSQL_PORT}
    environment:
      POSTGRES_USER: "${PSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: "${PSQL_NAME}"
  admin:
    image: adminer
    container_name: Database_Admin
    restart: always
    ports:
    - "${PSQL_ADMIN_PORT}:${PSQL_ADMIN_PORT}"
  fastapi:
    build: ./
    container_name: FastAPI
    environment:
      - RUST_BACKTRACE=1
      - PSQL_USERNAME=${PSQL_USERNAME}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_HOST=${PSQL_HOST}
      - PSQL_NAME=${PSQL_NAME}
      - PSQL_PORT=${PSQL_PORT}
      - PSQL_SSLMODE=${PSQL_SSLMODE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - DEBUG=${DEBUG}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - indexhub_local

  frontend:
    build: ./frontend
    container_name: React_Frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
       - ./frontend:/app
       - /app/node_modules
    depends_on:
      - fastapi
