version: '3.8'
services:
  fastapi:
    build:
      context: ./
      dockerfile: ./indexhub/Dockerfile
    container_name: fastapi
    environment:
      ENV_NAME: dev
      RUST_BACKTRACE: 1
      PSQL_DBNAME: ${PSQL_DBNAME}
      PSQL_PORT: ${PSQL_PORT}
      PSQL_USERNAME: ${PSQL_USERNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_HOST: ${PSQL_HOST}
      PSQL_SSLMODE: require
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      MODAL_TOKEN_ID: ${MODAL_TOKEN_ID}
      MODAL_TOKEN_SECRET: ${MODAL_TOKEN_SECRET}
    volumes:
      - ./indexhub:/app/indexhub
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    container_name: frontend
    environment:
      REACT_APP_AUTH0_DOMAIN: ${REACT_APP_AUTH0_DOMAIN}
      REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
      REACT_APP_INDEXHUB_API_AUDIENCE: ${REACT_APP_INDEXHUB_API_AUDIENCE}
      REACT_APP_INDEXHUB_API_CLIENT_ID: ${REACT_APP_INDEXHUB_API_CLIENT_ID}
      REACT_APP_INDEXHUB_API_CLIENT_SECRET: ${REACT_APP_INDEXHUB_API_CLIENT_SECRET}
      REACT_APP_INDEXHUB_API_DOMAIN: ${REACT_APP_INDEXHUB_API_DOMAIN}
      REACT_APP_INDEXHUB_API_DOMAIN_WEBSOCKET: ${REACT_APP_INDEXHUB_API_DOMAIN_WEBSOCKET}
      REACT_APP_AUTH0_MGMT_API_AUDIENCE: ${REACT_APP_AUTH0_MGMT_API_AUDIENCE}
      FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - fastapi
    ports:
      - 3000:3000
