version: '3.8'
services:
  indexhub_local:
    image: postgres:10-alpine
    container_name: PG_Database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
  admin:
    image: adminer
    container_name: Database_Admin
    restart: always
    ports:
    - "${POSTGRES_ADMIN_PORT}:${POSTGRES_ADMIN_PORT}"
  fastapi:
    build: ./
    container_name: FastAPI
    environment:
      - RUST_BACKTRACE=1
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - indexhub_local

  frontend:
    build: ./frontend
    container_name: React_Frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
       - ./frontend:/app
       - /app/node_modules
    depends_on:
      - fastapi
