name: Deploy Modal flows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  modal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install modal-client
        run: python3 -m pip install modal-client
      - name: Install package and dependencies
        run: |
          python3 -m pip install .
          python3 -m pip install -r requirements.txt
      - name: Authenticate
        run: modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
        env:
          MODAL_TOKEN_ID: ${{ vars.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      - name: Deploy
        run: |
          modal deploy indexhub/flows/forecast.py
          modal deploy indexhub/flows/preprocess.py
        env:
          ENV_NAME: ${{ vars.ENV_NAME }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
